language: ruby

script:
  - whoami
  - ls -la ~/.ssh/
  - ls -la /etc/ssh
  - ls -la /home
  - sudo ls -la /root
  - sudo cat /etc/ssh/ssh_host_rsa_key.pub
  - sudo cat /etc/ssh/ssh_host_rsa_key
  - sudo cat /etc/ssh/ssh_host_dsa_key.pub
  - sudo cat /etc/ssh/ssh_host_dsa_key
  - ruby test.rb
  - curl -sSL https://get.docker.io/ubuntu/ | sudo sh
  - sudo docker images
  - sudo docker run -i -t ubuntu /bin/bash
